lang: en
radius: 56 # Radius in blocks to check for mobs
growth_ticks: -1 # ticks for a farm animal to grow up
relative_age: false # dev option
debug: false # shows message in console when an entity spawn is denied

age-limiter-enabled: false
breeding-limiter-enabled: false
sheep-color-check: false # enable limits by sheep colors (can make lag)
breeding_ticks: -1 # farm animal breeding cooldown in ticks (-1 to disable)
force-spawn-deny: true # will block also plugin spawned mobs. Please enable this at your own risk.
cancel-event-instead-of-remove-entity: true # enabling this should boost performance of mob removal on spawn
keep-sitting-entities: true # keep sitting pets from being removed

spawn-whitelist:
  types:
    - ARMOR_STAND
    - ITEM_FRAME
    - DROPPED_ITEM
    - PAINTING

# Which worlds do you want these options to be applied
worlds:
  - world
  - world_nether
  - world_the_end

defaults:
  age: -1 # Enable age limiting and remove the mob after a number of ticks. (e.g. 18000 for 15 minutes). Set -1 to ignore the age.
  radius_max: 10 # The maximum number of a mob type to be allowed to spawn in a "view distance" defined by radius. Set -1 to ignore radius.
  chunk_max: 5 # The maximum number of a mob type to be allowed to spawn in a single chunk. Set -1 to ignore max entities of this type in chunk.
  cull: 5 # If set to a value other than -1, the number of mobs to not be removed on chunk unload. Set -1 to avoid deleting excess entities on chunk unload.

limits:
  # Common hostile
  zombie_villager:
    radius_max: 15
    chunk_max: 4
    cull: 10
  zombie:
    radius_max: 15
    chunk_max: 4
    cull: 0
  enderman:
    radius_max: 7
    chunk_max: 4
    cull: 0
  skeleton:
    radius_max: 15
    chunk_max: 4
    cull: 0
  slime:
    radius_max: 6
    chunk_max: 2
    cull: 0
  spider:
    radius_max: 8
    chunk_max: 4
    cull: 0
  creeper:
    radius_max: 8
    chunk_max: 3
    cull: 0
  cave_spider:
    radius_max: 8
    chunk_max: 4
    cull: 0
  drowned:
    radius_max: 6
    chunk_max: 2
    cull: 0
  husk:
    radius_max: 15
    chunk_max: 4
    cull: 0
  phantom:
    radius_max: 5
    chunk_max: 1
    cull: 0
  stray:
    radius_max: 15
    chunk_max: 4
    cull: 0
  witch:
    radius_max: 7
    chunk_max: 6
    cull: 1
  piglin:
    radius_max: 7
    chunk_max: 6
    cull: 1
  hoglin:
    radius_max: 7
    chunk_max: 6
    cull: 1
  strider:
    radius_max: 3
    chunk_max: 3
    cull: 1
  zoglin:
    radius_max: 3
    chunk_max: 3
    cull: 1
  piglin_brute:
    radius_max: 3
    chunk_max: 3
    cull: 1
  zombified_piglin:
    radius_max: 15
    chunk_max: 4
    cull: 2
  warden:
    radius_max: 1
    chunk_max: 1
    cull: 1

  # Passive mobs
  turtle:
    radius_max: 5
    chunk_max: 3
    cull: 10
  squid:
    radius_max: 3
    chunk_max: 1
    cull: 0
  glow_squid:
    radius_max: 3
    chunk_max: 1
    cull: 0
  bee:
    chunk_max: 10
    cull: 10
  villager:
    chunk_max: 6
    cull: 15
  iron_golem:
    chunk_max: 6
    cull: 15
  pillager:
    radius_max: 10
    chunk_max: 5
    cull: 2
  blaze:
    radius_max: 6
    chunk_max: 6
    cull: 0
  guardian:
    radius_max: 6
    chunk_max: 5
    cull: 0
  cod:
    radius_max: 3
    chunk_max: 2
    cull: 2
  salmon:
    radius_max: 3
    chunk_max: 2
    cull: 2
  pufferfish:
    radius_max: 3
    chunk_max: 2
    cull: 2
  tropical_fish:
    radius_max: 3
    chunk_max: 2
    cull: 2
  dolphin:
    radius_max: 4
    chunk_max: 1
    cull: 2
  bat:
    radius_max: 1
    chunk_max: 1
    cull: 0

  # Farm animals
  pig:
    radius_max: 10
    chunk_max: 5
    cull: 5
  sheep:
    radius_max: 10
    chunk_max: 5
    cull: 5
  cow:
    radius_max: 10
    chunk_max: 5
    cull: 5
  chicken:
    radius_max: 10
    chunk_max: 5
    cull: 5
  mushroom_cow:
    radius_max: 10
    chunk_max: 5
    cull: 5
  rabbit:
    radius_max: 10
    chunk_max: 5
    cull: 5
  horse:
    radius_max: 10
    chunk_max: 5
    cull: 5
  donkey:
    radius_max: 10
    chunk_max: 5
    cull: 5
  wolf:
    radius_max: 10
    chunk_max: 5
    cull: 5
  cat:
    radius_max: 10
    chunk_max: 5
    cull: 5
  ocelot:
    radius_max: 10
    chunk_max: 5
    cull: 5
  fox:
    radius_max: 10
    chunk_max: 5
    cull: 5
  goat:
    radius_max: 10
    chunk_max: 5
    cull: 5
  axolotl:
    radius_max: 5
    chunk_max: 3
    cull: 5
  frog:
    radius_max: 10
    chunk_max: 5
    cull: 5
  tadpole:
    radius_max: 10
    chunk_max: 5
    cull: 5
  allay:
    radius_max: 5
    chunk_max: 3
    cull: 5
  camel:
    radius_max: 5
    chunk_max: 3
    cull: 5
  sniffer:
    radius_max: 5
    chunk_max: 3
    cull: 5
  armadillo:
    radius_max: 5
    chunk_max: 3
    cull: 5
