tps-commands:
  enabled: false
  _INFO:
    - "You can use these placeholders in commands: {tps}"
    - "You can create as many as groups you want. Also commands are unlimited."
  commands:
    group_1:
      tps: 16
      delay_ticks: 36000
      list:
        command_1:
          command: "broadcast Server is lagging ({tps} tps). Please be patient."
          delay_ticks: 0
        command_2:
          command: "broadcast Removing entities on the ground in 60 seconds..."
          delay_ticks: 20
        command_3:
          command: "minecraft:kill @e[type=item]"
          delay_ticks: 1200
    group_2:
      tps: 14
      delay_ticks: 18000
      list:
        command_1:
          command: "broadcast Critical lag detected! ({tps} tps)"
          delay_ticks: 0
